demo_sea_events = [
    {
        "uuid": "adf8b2e0-aca4-404b-9342-f69e5013545f",
        "shipName": "IBIS (FRANCE)",
        "eventType": "Collision avec un iceberg",
        "occurrenceDate": "2020-01-01",
        "occurrenceTime": "00:00:00",
        "occurrenceNationalId": "0283",
        "notificationDate": "2020-01-01",
        "notificationTime": "00:00:00",
        "notificationEntity": "CROSS Jobourg",
        "directive_2009_18": "directive-2009-18-1",
        "coastalState": "France",
        "longitude": "43.079214",
        "lattitude": "3.514669",
        "callSign": "call-sign",
        "flagState": "France",
        "grossTonnage": "140T",
        "builtYear": "2006",
        "hullMaterial": "steel",
        "propulsionType": "electrical",
        "nationalLocation": "national-location",
        "registryNumber": "712369",
        "IMO": "91236410",
        "occurrenceSeaArea": "mediterranean sea",
        "shipType": "Chalutier",
        "overallLength": "30 m",
        "nbLivesLost": "0",
        "nbInjuredPeople": "1",
        "nbMissingPeople": "0",
        "processingStatus": "to-process",
    },
    {
        "uuid": "326adf8b2e0-aca4-404b-9342-f69e5013545h",
        "shipName": "MOINEAU (FRANCE)",
        "eventType": "Collision avec un autre navire",
        "occurrenceDate": "2021-02-02",
        "occurrenceTime": "00:00:00",
        "occurrenceNationalId": "0246",
        "notificationDate": "2021-02-02",
        "notificationTime": "00:00:00",
        "notificationEntity": "CROSS Brest",
        "directive_2009_18": "directive-2009-18-1",
        "coastalState": "France",
        "longitude": "43.079214",
        "lattitude": "3.514669",
        "callSign": "call-sign",
        "flagState": "France",
        "grossTonnage": "130T",
        "builtYear": "2008",
        "hullMaterial": "plastic",
        "propulsionType": "electrical",
        "nationalLocation": "national-location",
        "registryNumber": "1234512",
        "IMO": "8910111",
        "occurrenceSeaArea": "mediterranean sea",
        "shipType": "Chalutier",
        "overallLength": "28 m",
        "nbLivesLost": "0",
        "nbInjuredPeople": "0",
        "nbMissingPeople": "0",
        "processingStatus": "to-process",
    },
]
