# Generated by Django 3.2.13 on 2022-05-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry_helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='national_id',
            new_name='registration_number',
        ),
    ]
