# Generated by Django 3.2.13 on 2022-05-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entry_helper", "0003_rename_name_report_ship_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.TextField(default="todo"),
        ),
    ]
