name: Test workflow

on: [pull_request]
env:
  SEA_EVENT_MANAGER_SECRET_KEY: x^7pz2d(06mt_mi%$_kjf@+3xcg--v&ufcmv_n-ax7awmv0f3
  SEA_EVENT_MANAGER_ALLOWED_HOSTS: 127.0.0.1,0.0.0.0,localhost
  SEA_EVENT_MANAGER_EMCIP_URL: http://emcip_placeholder_url.com
  SEA_EVENT_MANAGER_BASIC_AUTHORIZATION_TOKEN: =not_the_token_you_are_looking_for
  RAW_REPORTS_DB_USERNAME: db_username
  RAW_REPORTS_DB_PASSWORD: db_password
  RAW_REPORTS_DB_HOST: db_host
  RAW_REPORTS_DB_PORT: 5432
  RAW_REPORTS_DB_DATABASE: db_database

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install poetry
      run: pip install poetry
    - name: Install requirements
      run: poetry install
    - name: Run tests
      run: poetry run python3 src/manage.py test
